import { GetServerSideProps } from 'next';
import Head from 'next/head'

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users')
  const userData = await res.json()
  return {
    props: {
      user : userData
    }
  };
};


export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
      {props.user.map((user)=> (
        <div key={user.id}>my name is {user.name}</div>
      ))}
     </main>
    </>
  )
}



